### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by Jerrodly** [falstack/vue-hybird-best-practices#1]
运行起来特别卡，用chrome devtools 的performance monitor一下，发现耗时都在script，还有图片资源一直pending

**Comment by falstack** [comment]
图片是使用的国外公开源，那么没关系，这个 demo 用的是瀑布流，每个元素都绝对定位的确性能表现很差，（一般也不会这么多个 tab 的瀑布流）我在考虑换成普通的数据流做展示了

**Comment by falstack** [comment]
### 这边可以看到在不限频的情况下的性能表现：

![image](https://user-images.githubusercontent.com/16357724/62598323-99f90480-b91b-11e9-8565-87346b6512ef.png)


### 如果限频到 6 倍的性能表现：

![image](https://user-images.githubusercontent.com/16357724/62598385-cd3b9380-b91b-11e9-9371-ecfe12a260b6.png)

主要是 Vue.js 内部在做更新了，这个优化起来比较吃力，我后续再想办法

**Comment by falstack** [comment]
这次的优化效果：

![image](https://user-images.githubusercontent.com/16357724/62666943-17725280-b9b8-11e9-925e-7609beef0849.png)

你可以尝试一下 demo，如果还是感觉卡顿我再来做优化

**Comment by falstack** [comment]
@gongxiansheng 旧版本是支持了保持当前 tab 在中间，但因为每次切换 tab 都要通过 `getBoundingClientRect` 去计算前后两个 tab 是否在视口内，就有性能问题

这个地方后续我会再想办法优化

**Comment by falstack** [comment]
@gongxiansheng tab 定位已经实现

**Comment by gongxiansheng** [comment]
@falstack 厉害，左滑滑到底，然后开始右滑是否也应该如左滑一样的体验呢

**Comment by falstack** [comment]
@gongxiansheng 左滑展示后一个，右滑展示前一个，现在的逻辑没问题
