### ISSUE TITLE
功能增加

### ISSUE THREAD

**Issue by alicksnake22** [falstack/vue-hybird-best-practices#2]
首先感谢，功能做得很好，也解决了很多问题。然而还是想问一下，类似淘宝首页和闲鱼首页那种Nestedscrollview的功能，如何在这里实现？就是，轮播区域也可以进行上下滑动，滑动一定距离后tab置顶，下面的继续滑。

**Comment by falstack** [comment]
`v-switcher` 没有对轮播做很强的支持，还没法做到`垂直轮播`和`3D轮播`等
`tab` 吸顶如果是 PC 可以使用`fixedTop`这个 props 来设置，如果是 H5 可以设置`sticky`为 true

详见 [v-switcher 文档](https://github.com/falstack/v-switcher)

**Comment by alicksnake22** [comment]
@falstack 我的意思并不是说垂直轮播，而是我说demo的tab以上的区域能否接收到触摸，然后进行整体的上下滑动？不是指滑动轮播，而是指滑动整个页面，然后滑动到一定距离tab就置顶了
