### ISSUE TITLE
下拉刷新问题

### ISSUE THREAD

**Issue by ajesses** [falstack/vue-hybird-best-practices#4]
你好，下拉刷新的时候，列表数据清空了，渲染效果显得很突兀，能否加个类似属性，控制它刷新后列表先不情况，之后再重新渲染呢

**Comment by falstack** [comment]
[this.$refs.loader.refresh(true)](https://falstack.github.io/vue-mixin-store/params.html#refresh-reload-false)

**Comment by ajesses** [comment]
试过了，不是刷新的时候不展示loading，是刷新的时候该列表的原有数据暂时不清空，请求完接口后list再刷新啊（类似cube-ui里的https://didi.github.io/cube-ui/#/zh-CN/docs/scroll 3customized里的例子），原生app那种下拉刷新

**Comment by falstack** [comment]
@ajesses 我发的那个 API 就可以实现你的需求，不展示 loading 也不清空之前的数据

[refresh-component](https://github.com/falstack/vue-hybird-best-practices/blob/master/examples/components/Refresher.vue)

这个项目里有一个 refresh 的组件，你可以用 [h5-vue-scroller](https://github.com/falstack/h5-vue-scroller) 的 refresh 和 refresh-end 方法来实现它

**Comment by falstack** [comment]
@ajesses 我更新了 demo，你可以看看

**Comment by ajesses** [comment]
好的，我看看，谢大佬
